- usr/Makefile
This PR fixs the following error when installing.
```
root@chttl3:~/src/mhvtl# make install
make usr
make[1]: Entering directory '/root/src/mhvtl'
make -C usr USR=vtl GROUP=vtl MHVTL_HOME_PATH=/opt/mhvtl MHVTL_CONFIG_PATH=/etc/mhvtl
make[2]: Entering directory '/root/src/mhvtl/usr'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/src/mhvtl/usr'
make[1]: Leaving directory '/root/src/mhvtl'
make -C usr install /usr/lib /usr
make[1]: Entering directory '/root/src/mhvtl/usr'
install -d -m 755 /usr/lib
install -o root -g  -m 755 libvtlscsi.so /usr/lib/
install: invalid group ‘-m’
Makefile:225: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/root/src/mhvtl/usr'
Makefile:75: recipe for target 'install' failed
make: *** …
```
> Fix install error

- .gitignore
- kernel/mhvtl.c
- usr/stklxx_pm.c
Just a small fix so that it compiles on CentOS 7 with a 3.10 kernel as well as >4,14 ones.
> 4.14 fix to compile on < 4.14 kernels

- .gitignore
- kernel/mhvtl.c
- usr/stklxx_pm.c
This pull request includes changes from Martin Wilck as 4.15 requires 4.14 changes.
This fixes issue #16 and I tested the compilation against olders 3.xx kernels.
> fix for 4.15 kernel timer API change

- usr/tapeexerciser.c
- usr/vtllib.c
This fixes issues found by gcc7 having to do with string copies that can truncate data.
> Fix simple compiler ussues

- etc/mhvtl.in
The init file left the Required-Stop field
blank, and it should instead contain "$null".
Also, add a Short-Description field.
> Fix two small init-file issues.

- usr/dump_tape.c
dump_tape was core dumping when trying to print a usage message for running it without any arguments. While fixing that, fix the usage in general, consolidate/unify error messages, and be more friendly in general.
> Fix dump_tape help msg, and dump_tape in general

- usr/hp_smc_pm.c
- usr/hp_ultrium_pm.c
- usr/ibm_smc_pm.c
- usr/overland_pm.c
- usr/quantum_dlt_pm.c
- usr/scalar_pm.c
- usr/stklxx_pm.c
- usr/ult3580_pm.c
- usr/vtllib.c
- usr/vtllib.h
- usr/vtllibrary.c
- usr/vtltape.c
The newer gcc7 compiler catches a class of error
where a truncated string printf can loose data. So
fix all of those.
> Fix string print overruns.

- man/Makefile
Use ChangeLog date instead of build date in man-page headers
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good.
This date call works with GNU date and BSD date (e.g. MacOSX).
> Use ChangeLog date instead of build date

- usr/vtl_cart_type.c
- usr/vtlcart.c
- usr/vtllibrary.c
- usr/vtltape.c
The gcc7 compiler, using the "-Werror=stringop-truncation" option,
is quite picky about possible string truncation, so cleanup ctring
usage to make it (and our program) happier.
There should be *no* functional changes.
> Cleanup string usage to make gcc7 happy.

- etc/vtllibrary@.service.in
- etc/vtltape@.service.in
The templates for vtltape and vtllibrary should run
before mhvtl.target, not multi-user.target.
Reported-by: Frank Bui <fbui@suse.com>
> correct vtltape and vtllibrary service dependencies

- usr/mktape.c
Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
Without this patch, `/var/lib/mhvtl/CLN101L4/meta` and other meta files
differed for every build.
```diff
00000100  54 4c 43 4c 4e 31 30 31  4c 34 5f 31 35 35 34 32  |TLCLN101L4_15542|
-00000110  30 39 32 32 36 00 00 00  00 00 00 00 00 00 00 00  |09226...........|
+00000110  30 39 33 30 32 00 00 00  00 00 00 00 00 00 00 00  |09302...........|
00000120  00 00 00 00 03 80 00 00  00 7f 00 00 00 00 00 00  |................|
-00000130  00 00 31 35 35 34 32 30  39 32 32 36 00 00 46 46  |..1554209226..FF|
+00000130  00 00 31 35 35 34 32 30  39 33 30 32 …
```
> Allow to override build date with SOURCE_DATE_EPOCH

- .gitignore
- vagrant/Vagrantfile
- vagrant/install.sh
Currently this is working for Ubuntu and Centos, but not for opensuse. You can test it by:
`cd vagrant`
and then
`vagrant up ubuntu`
or
`vagrant up centos`
or
`vagrant up opensuse`
I think its good to have this kind or some kind of end-to-end (installation on dist) testing for this project.
> Add Vagrant file with install script for testing

- vagrant/Vagrantfile
The `centos7` Vagrantbox is not available on https://app.vagrantup.com/boxes/search so I changed it to one that is publicly available.
> Change Vagrantbox for Centos to one that is  publicly available

- kernel/mhvtl.c
This field was removed in upstream linux commit:
>  aaff5ebaa269 ("scsi: remove the unchecked_isa_dma flag")
And mhvtl didn't use it (set it to "1") anyway.
> Handle scsi_host_template removal of unchecked_isa_dma.

- INSTALL
I attempted to install on Linux Mint 20.
The package name of sg3_utils in the Install doc used an underscore not a hyphen.
This pull request updates the install doc.
> Fix: Incorrect sg3_util package name in install instructions

- man/edit_tape.1.in
- man/mktape.1.in
- man/vtllibrary.1.in
I found the man pages mktape and edittape refer to T10Kb tapes instead of T10KB tapes. I think this is an error as default_ssc_pm.c, t10000_pm.c and vtllib.c all use the latter.
Also the man page for vtllibrary incorrectly refers to the HOME_PATH as the location of the library_contents.* files. This has been changed to CONFIG_PATH.
> Doc: Fix VTLlibrary man page error. Fix: man page typo T10Kb -> T10KB

- usr/tape_util.c
The vendor ID field is 9 bytes long, and we are writing 9
bytes to it, so there is no room for the NULL, making
strncpy() and the compiler unhappy. Just copy one less
bytes.
> Silence compiler complaints about string too long

- .gitignore
- Makefile
- config.mk
- etc/Makefile
- kernel/Makefile
- man/Makefile
- scripts/Makefile
- tcopy/Makefile
- usr/Makefile
Centralise tweakable bits and bobs into `config.mk` which sub-Makefiles
include; `local.mk` (`.gitignore`'d) can be used to specify site-specific
overrides.
> Makefile infrastructure: fix passing variables

- etc/Makefile
- usr/mhvtl-device-conf-generator.c
I was a bit quick to cancel the other one - here's one anew. Instead of dropping the explicit shell
invocation, use the correct shell then to invoke the scripts with.
> etc/Makefile: invoke bash scripts using 'bash', not 'sh'

- usr/vtlcart.c
- usr/vtlcart_v1.c
- usr/vtlcart_v1_mtr.c
The creat() interface is considered to have been obsoleted by open():
https://pubs.opengroup.org/onlinepubs/9699919799/functions/creat.html
> vtlcart: Replace calls to creat() with calls to open()

- kernel/Makefile
- kernel/backport.h
- kernel/config.sh
- kernel/mhvtl.c
This fixes a build issue for the kernel module, so that it handles the recent remove of <genhd.h>. While I was there, I cleaned up config.sh, and I fixed an issue with HAVE_UNLOCKED_IOCTL by moving it into config.sh. The kernel Makefile's "clean" and "distclean" targets were cleaned up, as well.
Tested on kernels 5.18 (openSUSE Tumbleweed) and 5.3 (openSUSE Leap 15.3).
> Fix removal of genhd

- kernel/config.sh
Commit:
> 6e8175315554 (fix-double-define-of-have_unlocked_ioctl) kernel:
>   Handle removal of genhd.h from linux includes.
moved definition of HAVE_UNLOCKED_IOCTL to config.sh/config.h,
but this new logic doesn't account for the fact that older
kernels define their own macro of the same name.
So put guards around the definition of HAVE_UNLOCKED_IOCTL, only
defining it if needed.
> Fix possible double define of HAVE_UNLOCKED_IOCTL

- usr/vtllib.c
If a file is written to a virtual tape device with a size that is 1,2 or 3 bytes larger than the a multiple of 2MB (including zero), the write will drop the additional bytes.
I have create a test script here:
https://gist.github.com/nrichtapeark/269ebc51563af6800acad18aef513ca6
> Change minimum block size to 1 byte to prevent data loss when writing file on size boundary

- kernel/config.sh
- kernel/mhvtl.c
This makes choosing how to call mhvtl_queuecommand_lck() semantic rather than version-based, as we now look and see if we need one argument or two, instead of assuming the result based on kernel version. This handles the cases where distributions back-port this change to earlier kernels.
> Handle queuecommand arg change

- usr/vtltape.c
Reproducing same steps I undertook locally to get mhvtl compiling. But without really taking the time to fully understand the history behind the cause of this compilation error (whether this was a new variable introduced or whether the declaration had been removed).
> Add used, but undeclared variable fg into vtltape::processMessageQ() function

- kernel/config.sh
- kernel/mhvtl.c
Upstream kernel 6.4 modified the DEFINE_SEMAPHORE() macro so that it takes a numeric argument. Handle that case, when needed, by checking in config.sh and handling both options in mhvtl.c
> Fix issue with DEFINE_SEMAPHORE in kernel module

- Makefile
This patch is as simple as possible.
For this it assumed that the consumer understands GNU tar format
and does not care about mtimes.
This patch was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
> Normalize tar file

- kernel/config.sh
- kernel/mhvtl.c
This fixes one existing config.sh/config.h kernel module build issue (for 6.4 kernel), and it adds a fix for a new kernel build issue (for 6.11 kernel).
> Fix kernel build issue

- usr/make_vtl_media.in
Barcodes with a leading "W" indicate WORM media. make_vtl_media detects the media type by parsing the barcode and calls mktape with the appropriate arguments. This bug resulted in mktape being called with "-t work" instead of "-t WORM".
> Fix bug in make_vtl_media that prevents detection of WORM media

- kernel/mhvtl.c
If CONFIG_PREEMPT_RT is defined, as it is for the new SUSE kernel, where Real Time has been enabled, usage of the __SPIN_LOCK_UNLOCKED() macro fails to compile:
```
[   39s] + make -C /usr/src/linux-obj/x86_64/rt 'EXTRA_CFLAGS=-Iinclude -DMHVTL_DEBUG -DHAVE_UNLOCKED_IOCTL' modules M=/home/abuild/rpmbuild/BUILD/mhvtl-1.72_release+0.70719883aae2-build/mhvtl-1.72_release+0.70719883aae2/obj/rt
[   39s] make: Entering directory '/usr/src/linux-6.12.0-160000.11-obj/x86_64/rt'
[   40s]   CC [M]  /home/abuild/rpmbuild/BUILD/mhvtl-1.72_release+0.70719883aae2-build/mhvtl-1.72_release+0.70719883aae2/obj/rt/mhvtl.o
[   40s] In file included from /usr/src/linux-6.12.0-160000.11/include/linux/mutex_types.h:8,
[   40s]                  from /usr/src/linux-6.12.0-160000.11/include/linux/sched.h:25,
[ …
```
> mhvtl: kernel: fix build issue if RealTime kernel

- usr/vtltape.c
The response of the READ ATTRIBUTE command is prefixed with a 4-byte length.
By returning `ret_val`, the response is truncated by 4-byte.
> Fix returned length of READ ATTRIBUTE response
